import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Banner, Header } from "../components/index";

export default function Home() {
	return (
		<div className="relative h-screen bg-gradient-to-b from-gray-900/10 to-[#010511] lg:h-[140vh]">
			<Head>
				<title>Netflix clone app</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main>
				<Banner />
			</main>
		</div>
	);
}
