import Head from "next/head";
import Image from "next/image";

function login() {
	return (
		<div className="relative flex h-screen w-screen flex-col bg-black md:items-center md:justify-center md:bg-transparent">
			<Head>
				<title>Netflix</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Image src="/assets/netflix-bg.jpg" className="-z-10  opacity-60 sm:!inline" layout="fill" objectFit="cover" alt={"login-bg"} />
			<Image
				src="https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg"
				alt="netflix-logo"
				width={100}
				height={100}
				className="cursor-pointer object-contain absolute left-4 top-4 md:left-10 md:top-6"
			/>

			<form className="relative mt-24 space-y-8 rounded bg-black/75 py-10 px-6 md:mt-0 md:max-w-md md:px-14">
				<h1 className="text-4xl font-semibold">Sign In</h1>
				<div className="space-y-4">
					<label className="inline-block w-full">
						<input type="email" placeholder="Email" className="input" />
					</label>
					<label className="inline-block w-full">
						<input type="password" placeholder="Password" className="input" />
					</label>
				</div>
				<button className="w-full rounded bg-[#E50914] py-3 font-semibold" type="submit">
					Sign In
				</button>
				<div className="text-[gray]">
					New to Netflix?{" "}
					<button className="cursor-pointer text-white hover:underline" type="submit">
						Sign up now
					</button>
				</div>
			</form>
		</div>
	);
}

export default login;
